### ISSUE TITLE
Unexpected behavior with a singleton actor server outage when queued messages are pending

### ISSUE THREAD

**Issue by eaepstein** [IBM/kar#102]
[queued-msg-problem.zip](https://github.com/IBM/kar/files/6394147/queued-msg-problem.zip)

scenario 1: stop and restart actor server with queued messages (works)
1. start server: kar run -app queue -actors Stateful -- node stateful-server.js
2. create queue of messages: kar run -app queue -actors Stateful -- node queue-stateful.js 10
3. before queue is fully processed, kill and restart actor server
result: actor server continues processing queued messages after restart

scenario 2: same as s1, but with a client interacting with the actor during the outage (hangs)
1. start server as in s1 above
2. start probe-client: kar run -missing_component_timeout 0 -app queue -actors Stateful -- node probe-stateful.js
3. create queue of messages as in s1 above
4. before queue is fully processed, kill actor server, wait 10 seconds and restart actor server
result: actor server will not process any more queued messages until probe-client is killed
note: if there are two actor server instances, the actor immediately migrates to the other server and all works

scenario 3: same as s2, but only kill and restart server when no messages are queued (works)
1. start server as in s1
2. start probe-client as in s1
3. create queue of messages and let them complete processing
4. kill and restart actor server
5. reset server state: kar invoke -app queue Stateful singleton clear (works)
result: probe reports that the server state has changed

**Comment by dgrove-oss** [comment]
I can reproduce a hang in scenario 2, but it only happens some of the time.  (some of the time, things recover just fine).  Looks to be dependent on exactly where each side is in the communication protocol when the server side is killed.

**Comment by dgrove-oss** [comment]
Very likely this will be fixed by the new Kafka-only roc library, but leaving open until we can verify
