### ISSUE TITLE
Kar cli echos application output to stderr

### ISSUE THREAD

**Issue by eaepstein** [IBM/kar#259]
This complicates monitoring of kar applications components running in containers with KAR_SIDECAR_IN_CONTAINER=true.
Examples are:
- grepping an application running in a docker container requires
`docker logs <container> 2>&1 | grep <something>`
- programmatic processing application output running in K8S reads stdout but must be modified to read stderr when the app is running in docker compose or podman play

Suggestion is for application output to go to stdout

**Comment by dgrove-oss** [comment]
Looked into this.  We are putting the kar sidecar, the application stdout, and the application stderr into a single unified output stream (funneling it all through Go's `log` package).  It just happens that the default output stream for the log packager is stderr, not stdout.  We can easily change this single stream to be stdout.
