### ISSUE TITLE
Redis & garbage collection

### ISSUE THREAD

**Issue by tardieu** [IBM/kar#30]
We only clear the completion status of past requests in Redis when the Kafka group is rebalanced. As a consequence, in a stable system (no KAR component added or removed), the Redis footprint keeps growing leading to increased latency. We need more/better triggers for this garbage collection.

As a temporary workaround, a couple of dummy `kar invoke` commands can force a garbage collection.

**Comment by dgrove-oss** [comment]
Obsolete as of KAR 1.3.  rpclib does not use Redis to store completion status and the previous transport implementation that did use Redis was removed.
