### ISSUE TITLE
actor_busy_timeout broken with rpclib transport

### ISSUE THREAD

**Issue by eaepstein** [IBM/kar#349]
The -actor_busy_timeout setting is non-functional.
Method calls that take more than 120 seconds will return 404 when they do complete.

This bug seriously limits utility of KAR debugger breakpoints.

**Comment by dgrove-oss** [comment]
Writing this down so I remember; the command line is actually working correctly.  There is something going wrong elsewhere not directly related to the value that is set for actor_busy_timeout

**Comment by dgrove-oss** [comment]
fixed in #350
