### ISSUE TITLE
http/2 support for Java SDK

### ISSUE THREAD

**Issue by dgrove-oss** [IBM/kar#46]
To support higher levels of concurrency, we need to implement http/2 connections between the Java SDK and the `kar` sidecar.  This would match the functionality implemented in the JavaScript SDK to use http/2 on this communication link.

**Comment by paulcastro** [comment]
Just a note, there aren't any microprofile rest clients that support http/2 so we would need to replace this layer with a traditional implementation of a rest client.

**Comment by dgrove-oss** [comment]
The quarkus-based SDK now defaults to using http/2.
